### ISSUE TITLE
Quando completa um item não dá dinheiro

### ISSUE THREAD

**Issue by supermario64invisivel** [supermario64invisivel/Money-Adventure#1]

**Comment by jbruni** [comment]
Quando isso acontece? Eu estou testando o jogo agora, mas ainda não vi o erro.

Por favor, tente reproduzir o problema e me mostre. Obrigado.

**Comment by supermario64invisivel** [comment]
é pelo jeito voltou ao normal

**Comment by jbruni** [comment]
Acho que esse defeito só aparece quando é feita alguma atualização no código enquanto o jogo já está rodando.

Ou seja, é um problema relacionado ao "hot reload" do Webpack.
