### ISSUE TITLE
Adicionar index:all,index com mais de 1 item exemplo:1,4,2 e upgrade e achievement para tudo

### ISSUE THREAD

**Issue by supermario64invisivel** [supermario64invisivel/Money-Adventure#11]
Adicionar index:all para quando ganhar um achievement poder melhorar tudo
index com mais de um item permite que vc possa colocar + de 1 item ao mesmo tempo em um achievement sem ter que melhorar tudo exemplo:1,4,2
com os upgrades de tudo vc pode melhorar tudo comprando uma só vez preços:50 trillion*2,500 quintillion*3, 500 septillion*4,1 decillion *5
os achievements de tudo funcionam assim quando eu pegar x de tudo eu vou ganhar um achievement e melhorar tudo, achievements:25*2,50*2,100*2,150*2,200*2,250*2,300*2,400*2,500*2,600*2,750*2

**Comment by jbruni** [comment]
Feito:
- suporte para `index: 'all'` nos _achievements_ (melhora todos os itens de uma vez)
- suporte para `index: [1, 4, 2]` nos _achievements_ (melhora os itens especificados de uma vez)
- suporte para `index: 0` (corrigido)
- criado `achieveAll` para os _achievements_ ativados quando uma quantidade de **todos** os itens for atingida (`index: 'all'` usado se nenhum `index` for informado)

**Comment by jbruni** [comment]
Falta ainda os "upgrades de tudo". Vou criar outro ticket para isso.
